alias brc='vim ~/.bashrc'
alias brcrl='. ~/.bashrc'
alias cleanassets='be rake assets:clean:all'
alias gd='git diff --color'
alias gitgraph='git log --pretty=format:"%h %s" --graph'
alias gitsum='git log --pretty=format:"%h %s"'
alias gitol='git log --pretty=oneline'
alias gre='grep -r --color'
alias gs='git show --color'
alias ls='ls -G'
alias nt='vim -c NT'
alias rmswp='find . -name '\''*.swp'\'' -delete'
alias rs='be rspec'
alias sz='du -hs'
alias tp='be rake db:test:prepare'
alias gu='be guard'
alias nocop='be guard start -P rspec'
alias rlc='be rake log:clear'
alias pt='be rake parallel:spec[8];rlc'
alias ptp='be rake parallel:prepare'
alias updatedev='cd ~/dev/; for dir in *; do cd $dir; pwd; git pull -r; bundle install; rlc; cd ..; done;'
